### PR TITLE
Change file extension of temperory files to md

### PR DESCRIPTION
**Pull request by shubhamshuklaer**
Change the file extension of temporary files used for creating/editing
issues,comments and milestones to md(markdown).  The editor will
recoganize that its a markdown file and use markdown syntax
highlighting.

### CODE REVIEW

**Comment by shubhamshuklaer** [comment]
Correct file type can be very helpful. Apart from syntax highlighting, there can be many other editor functions associated with markdown file type like live preview in browser,syntax checking, code snippets, file type specific shortcuts, auto-complete.

**Comment by stephencelis** [comment]
Thanks for the PR! While I think this is generally the right direction, ghi currently follows in git's footsteps and uses the first line as the title and (trailing) lines prefixed with "#" as comments rather than Markdown headers. I wonder if, to avoid confusion, we need to also change these comments to be formatted differently (_e.g._, use `<!-- -->`-style commenting, which Markdown supports) before making such a change.

**Comment by shubhamshuklaer** [comment]
You are right. I didn't think about that. I also think making this change without changing the current format(git's) will be more confusing. 

However I think it will be better to switch away from the git format because of following reasons
* git's format isn't designed for markdown, they have their own file type and syntax highlighting( for eg. in vim they have file-type gitcommit, gitrebase etc)
* This software is designed for issues/comments/milestones etc.. Its not related to git but  with github's issue tracker. So I don't think we need to keep the format consistent with git.

Do you think switching away from git's format will be a useful? If it is, then I can work on that. It will take some time, as my exams are coming. I like this software and to be able to use  all markdown features of my editor will be cherry on top.

**Comment by shubhamshuklaer** [comment]
There is a bug in my change. While amending comment, the file name is of the form GHI_COMMENT_[issue_number].md_[some_comment_identifier] . The md should have been in the end. I will fix that.

**Comment by AlexChesters** [comment]
I'd be very wary about moving away from the Git approach; I think ghi's syntax for commenting etc should be as identical to Github Flavoured Markdown as possible. People should be able to write the same snippet on a ghi issue as a Github issue and have them behave the same in my opinion. 

I'd love to get @stephencelis's opinion on this though

**Comment by shubhamshuklaer** [comment]
@AlexChesters You misunderstood my point. I also want to keep the format identical to  Github Flavoured Markdown.  By git's format I meant the format and content of the file which appears when we do git commit. And that isn't Github Flavoured Markdown. 

The software removes the trailing lines starting with "#" before submitting to github, I only wish to change that. Instead of removing trailing lines starting with "#" we can remove trailing markdown style comment. The rest should be same.

**Comment by shubhamshuklaer** [comment]
We can also add just one "#" to the first line of issue, so that it shows as Heading while previewing locally and then remove it while submitting.

**Comment by shubhamshuklaer** [comment]
@AlexChesters  The "#" is used for heading in Github flavored markdown. As you can see in this comment. I used "# Test Heading" for that.
# Test Heading

**Comment by stephencelis** [comment]
With #287 working well and merged, this looks good to me. Thanks for your help!

**Pull request merged**
