### PR TITLE
Fix Socket NameError

### LINKED ISSUE #165: New set up from clean missing module, and fails to authorize
Two issues, really - a missing include (I think?), and then a failed storing of the token. Both highlighted by this transcript (nothing relevant in my global .gitconfig):

```
$ gem install ghi
$ ghi
Authorization required.
Please run 'ghi config --auth <username>'
$ ghi config --auth dracos
Enter dracos's GitHub password (never stored): /Users/matthew/.virtualenvs/ghitemp/gems/gems/ghi-0.9.3/lib/ghi/authorization.rb:23:in `authorize!': uninitialized constant Module::Socket (NameError)
    from /Users/matthew/.virtualenvs/ghitemp/gems/gems/ghi-0.9.3/lib/ghi/commands/config.rb:27:in `execute'
    from /Users/matthew/.virtualenvs/ghitemp/gems/gems/ghi-0.9.3/lib/ghi/commands/command.rb:17:in `execute'
    from /Users/matthew/.virtualenvs/ghitemp/gems/gems/ghi-0.9.3/lib/ghi.rb:80:in `execute'
    from /Users/matthew/.virtualenvs/ghitemp/gems/gems/ghi-0.9.3/bin/ghi:4:in `<top (required)>'
    from /Users/matthew/.virtualenvs/ghitemp/gems/bin/ghi:23:in `load'
    from /Users/matthew/.virtualenvs/ghitemp/gems/bin/ghi:23:in `<main>'
```

At this point I edit authorization.rb to have a `require "Socket"` at the top. Then:

```
$ ghi config --auth dracos
Enter dracos's GitHub password (never stored):       ✔
✔︎ Token saved to keychain.
$ ghi
⠞security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
#
Authorization required.

Please run 'ghi config --auth <username>'
```

After investigating with my limited ruby knowledge, I think what is happening is that the `unless username` calls `username` which sets `@username` from reading nothing from the git config, and then `store_token` is called with this blank cached username. Indeed, if I clear out the auth token from github and then run ghi config again (so with my .gitconfig now having the github.user line) it does successfully store the token in my keychain.

Hope that's helpful.

### PR DESCRIPTION
**Pull request by dracos**
Sorry, I don't know if this is the right way to fix this, but it worked for me. Part fixes #165.

### CODE REVIEW

**Comment by 0xMF** [comment]
I am getting this error too.

**Comment by rlouf** [comment]
Have you tried the fix proposed by cw0? It is not in the last release, but you can implement it by hand. I just installed ghi, had the same problem and cw0's suggestion fixed it.

**Comment by samertm** [comment]
Just to add my voice to the din: I hit this exception after installing ghi with gem.

**Comment by vicentebolea** [comment]
Same here, I also got this exception using the gem on ruby-head interpreter

**Comment by lpanebr** [comment]
Using the lower case `require "socket"` worked for me.

**Pull request merged**
