### PR TITLE
Fix SSL connection error message

### PR DESCRIPTION
**Pull request by martinmosegaard**
Should fix issue #351

### CODE REVIEW

**Comment by timofonic** [comment]
@drazisil Would you like to merge this to your repo?

**Comment by drazisil** [comment]
Merged into my repo with https://github.com/drazisil/ghi/pull/3

**Comment by martinmosegaard** [comment]
Hi @drazisil - great! Is your repo the successor of this one? Then I'll just close this PR.

**Comment by drazisil** [comment]
@martinmosegaard It can be if you wish. I saw this repo was quiet so I decided to merge some things :)

**Comment by martinmosegaard** [comment]
Repo seems stale.

**Pull request closed without merging**
