### PR TITLE
Remove json pure #277

### LINKED ISSUE #277: license: json-pure?
The following [fragment](../blob/master/LICENSE#L6) of `LICENSE` file is ambiguous:

    json-pure © Genki Takiuchi

Please clarify which part of _ghi_ is copyrighted as above. Thanks.

### PR DESCRIPTION
**Pull request by AlexChesters**
This PR would resolve #277 and it removes the use of `json-pure`.

### CODE REVIEW

**Comment by AlexChesters** [comment]
@stephencelis does this look like what you imagined? I've ran it myself and performed most of the commands and they all seem to work as expected.

**Comment by stephencelis** [comment]
Looks good! I do wonder if an explicit `require 'json'` is needed somewhere, though, depending on the user/platform.

**Comment by AlexChesters** [comment]
client.rb does now require it, I'm not sure if that is all that's needed?

**Comment by stephencelis** [comment]
LGTM! :+1:

**Pull request merged**
