### PR TITLE
Teach people about authing with a token

### PR DESCRIPTION
**Pull request by davidascher**
As discussed in #312.

### CODE REVIEW

**Comment by timofonic** [comment]
@drazisil Would you like to merge this to your repo?

**Comment by drazisil** [comment]
Merged into my repo here https://github.com/drazisil/ghi/pull/6

**Comment by brigand** [comment]
Instructions added to [the wiki](https://github.com/stephencelis/ghi/wiki/FAQ).

**Comment by robinmoussu** [comment]
The help message (when using ghi for the first time should also be changed):

```
Authorization required.

Please run 'ghi config --auth <username>'
```

**Pull request closed without merging**
