### PR TITLE
WIP: Pulls

### PR DESCRIPTION
**Pull request by LFDM**
Interface to GitHub's Pull Request API. Quite massive.

Will add a description at a later point, this is currently here for
easier referencing.
Very much work in progress with rough patches and some nasty bugs right now :)

### CODE REVIEW

**Comment by dennisschoenmakers** [comment]
Would love to use this!

**Comment by AlexChesters** [comment]
Hi @LFDM,

This is a great idea! I see this is a particularly large PR with merge conflicts that hasn't been touched in a while. Do you still intend to merge this in?

**Comment by karlhorky** [comment]
+1 would like to have this as well

**Comment by AlexChesters** [comment]
This is a great idea but seeing as how this is a particularly large PR, with merge conflicts, that is buggy I don't think we're in a position to merge this.

**Comment by AlexChesters** [comment]
I've created #256 for this

**Comment by dennisschoenmakers** [comment]
:+1:

**Pull request closed without merging**
